# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'artist_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArtistWindow(object):
    def setupUi(self, ArtistWindow):
        ArtistWindow.setObjectName("ArtistWindow")
        ArtistWindow.resize(457, 352)
        ArtistWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(144, 255, 0, 255), stop:0.465909 rgba(255, 162, 0, 255), stop:1 rgba(255, 21, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(ArtistWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo_label = QtWidgets.QLabel(self.centralwidget)
        self.photo_label.setGeometry(QtCore.QRect(60, 10, 151, 111))
        self.photo_label.setStyleSheet("background-color: rgb(116, 125, 150);\n"
"border: 3px solid rgb(255, 255, 255);\n"
"border-radius: 5px\n"
"")
        self.photo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_label.setObjectName("photo_label")
        self.info_text = QtWidgets.QTextEdit(self.centralwidget)
        self.info_text.setEnabled(True)
        self.info_text.setGeometry(QtCore.QRect(60, 140, 341, 151))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.info_text.setFont(font)
        self.info_text.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.426, y1:0.494, x2:0.42, y2:0.471, stop:0.244318 rgba(228, 203, 16, 255), stop:0.670455 rgba(138, 0, 0, 255));\n"
"color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px;\n"
"border:3px solid rgb(10, 55, 240);\n"
"border-radius: 10px")
        self.info_text.setReadOnly(True)
        self.info_text.setObjectName("info_text")
        self.label_artist = QtWidgets.QLabel(self.centralwidget)
        self.label_artist.setGeometry(QtCore.QRect(230, 10, 161, 21))
        self.label_artist.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_artist.setFont(font)
        self.label_artist.setAutoFillBackground(False)
        self.label_artist.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"background-color: qconicalgradient(cx:0.517045, cy:0.517, angle:0, stop:0 rgba(255, 0, 0, 255), stop:0.477273 rgba(89, 41, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"width: fit-content;\n"
"padding-left: 5px;")
        self.label_artist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_artist.setWordWrap(False)
        self.label_artist.setObjectName("label_artist")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(230, 40, 121, 21))
        self.label_date.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_date.setFont(font)
        self.label_date.setAutoFillBackground(False)
        self.label_date.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"background-color: qconicalgradient(cx:0.517045, cy:0.517, angle:0, stop:0 rgba(255, 0, 0, 255), stop:0.477273 rgba(89, 41, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"width: fit-content;\n"
"padding-left: 5px;")
        self.label_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_date.setWordWrap(False)
        self.label_date.setObjectName("label_date")
        self.label_country = QtWidgets.QLabel(self.centralwidget)
        self.label_country.setGeometry(QtCore.QRect(230, 70, 131, 21))
        self.label_country.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_country.setFont(font)
        self.label_country.setAutoFillBackground(False)
        self.label_country.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"background-color: qconicalgradient(cx:0.517045, cy:0.517, angle:0, stop:0 rgba(255, 0, 0, 255), stop:0.477273 rgba(89, 41, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"width: fit-content;\n"
"padding-left: 5px;")
        self.label_country.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_country.setWordWrap(False)
        self.label_country.setObjectName("label_country")
        self.labe_listeners = QtWidgets.QLabel(self.centralwidget)
        self.labe_listeners.setGeometry(QtCore.QRect(230, 100, 181, 21))
        self.labe_listeners.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labe_listeners.setFont(font)
        self.labe_listeners.setAutoFillBackground(False)
        self.labe_listeners.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"background-color: qconicalgradient(cx:0.517045, cy:0.517, angle:0, stop:0 rgba(255, 0, 0, 255), stop:0.477273 rgba(89, 41, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: rgb(255, 255, 255);\n"
"width: fit-content;\n"
"padding-left: 5px;")
        self.labe_listeners.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labe_listeners.setWordWrap(False)
        self.labe_listeners.setObjectName("labe_listeners")
        ArtistWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArtistWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 21))
        self.menubar.setObjectName("menubar")
        ArtistWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArtistWindow)
        self.statusbar.setObjectName("statusbar")
        ArtistWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ArtistWindow)
        QtCore.QMetaObject.connectSlotsByName(ArtistWindow)

    def retranslateUi(self, ArtistWindow):
        _translate = QtCore.QCoreApplication.translate
        ArtistWindow.setWindowTitle(_translate("ArtistWindow", "ArtistWindow"))
        self.photo_label.setText(_translate("ArtistWindow", "TextLabel"))
        self.label_artist.setText(_translate("ArtistWindow", "Artist name:"))
        self.label_date.setText(_translate("ArtistWindow", "birth date:"))
        self.label_country.setText(_translate("ArtistWindow", "country:"))
        self.labe_listeners.setText(_translate("ArtistWindow", "monthly listeners:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ArtistWindow = QtWidgets.QMainWindow()
    ui = Ui_ArtistWindow()
    ui.setupUi(ArtistWindow)
    ArtistWindow.show()
    sys.exit(app.exec_())
