# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        #Form.setObjectName("Form")
        Form.resize(483, 390)
        Form.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setStyleSheet("background-color: rgb(69, 91, 125);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 463, 370))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.innerWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.innerWidget.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.innerWidget.setObjectName("innerWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.innerWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 30, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.gridLayout.addWidget(self.innerWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.scroll_area()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


    def scroll_area(self):
        for i in range(0):
            text = f'Label {i+1}'
            label = QtWidgets.QLabel(text)
            label.setFixedSize(100, 120)
            label.setStyleSheet("background-color: rgb(233, 100, 122); font-size: 15px")
            self.verticalLayout1.addWidget(label)
        self.innerWidget.setLayout(self.verticalLayout1)
        self.innerWidget.setStyleSheet('padding-left: 5px;')




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
