# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'song_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SongWindow(object):
    def setupUi(self, SongWindow):
        SongWindow.setObjectName("SongWindow")
        SongWindow.resize(450, 346)
        SongWindow.setStyleSheet("background-color: qconicalgradient(cx:0.517045, cy:0.517, angle:0, stop:0 rgba(255, 0, 0, 255), stop:0.477273 rgba(89, 41, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(SongWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelArtist = QtWidgets.QLabel(self.centralwidget)
        self.labelArtist.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.labelArtist.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelArtist.setFont(font)
        self.labelArtist.setAutoFillBackground(False)
        self.labelArtist.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.102, y1:0.153, x2:0.915, y2:0.988409, stop:0 rgba(255, 23, 18, 255), stop:1 rgba(255, 212, 122, 255));\n"
"padding-left: 5px;\n"
"")
        self.labelArtist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelArtist.setWordWrap(False)
        self.labelArtist.setObjectName("labelArtist")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(30, 60, 161, 31))
        self.label_name.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.102, y1:0.153, x2:0.915, y2:0.988409, stop:0 rgba(255, 23, 18, 255), stop:1 rgba(255, 212, 122, 255));\n"
"padding-left: 5px;\n"
"")
        self.label_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_name.setObjectName("label_name")
        self.label_genre = QtWidgets.QLabel(self.centralwidget)
        self.label_genre.setGeometry(QtCore.QRect(250, 20, 171, 31))
        self.label_genre.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.102, y1:0.153, x2:0.915, y2:0.988409, stop:0 rgba(255, 23, 18, 255), stop:1 rgba(255, 212, 122, 255));\n"
"padding-left: 5px;\n"
"")
        self.label_genre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_genre.setObjectName("label_genre")
        self.label_likes = QtWidgets.QLabel(self.centralwidget)
        self.label_likes.setGeometry(QtCore.QRect(250, 60, 171, 31))
        self.label_likes.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.102, y1:0.153, x2:0.915, y2:0.988409, stop:0 rgba(255, 23, 18, 255), stop:1 rgba(255, 212, 122, 255));\n"
"padding-left: 5px;\n"
"")
        self.label_likes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_likes.setObjectName("label_likes")
        self.lyrics_text = QtWidgets.QTextEdit(self.centralwidget)
        self.lyrics_text.setEnabled(True)
        self.lyrics_text.setGeometry(QtCore.QRect(60, 140, 311, 171))
        self.lyrics_text.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0.165, y1:0.210227, x2:0.164773, y2:0.193, stop:0.176136 rgba(138, 0, 118, 255), stop:0.397727 rgba(97, 16, 106, 255));\n"
"font: 75 10pt \"Palatino Linotype\";\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px;\n"
"border: 2px solid rgb(255, 153, 28);")
        self.lyrics_text.setReadOnly(True)
        self.lyrics_text.setObjectName("lyrics_text")
        self.label_year = QtWidgets.QLabel(self.centralwidget)
        self.label_year.setGeometry(QtCore.QRect(170, 100, 91, 31))
        self.label_year.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0.102, y1:0.153, x2:0.915, y2:0.988409, stop:0 rgba(255, 23, 18, 255), stop:1 rgba(255, 212, 122, 255));\n"
"padding-left: 5px;\n"
"")
        self.label_year.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_year.setObjectName("label_year")
        SongWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SongWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        SongWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SongWindow)
        self.statusbar.setObjectName("statusbar")
        SongWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SongWindow)
        QtCore.QMetaObject.connectSlotsByName(SongWindow)

    def retranslateUi(self, SongWindow):
        _translate = QtCore.QCoreApplication.translate
        SongWindow.setWindowTitle(_translate("SongWindow", "sing_window"))
        self.labelArtist.setText(_translate("SongWindow", "Artist: "))
        self.label_name.setText(_translate("SongWindow", "name: "))
        self.label_genre.setText(_translate("SongWindow", "genre: "))
        self.label_likes.setText(_translate("SongWindow", "youtube likes: "))
        self.label_year.setText(_translate("SongWindow", "year: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SongWindow = QtWidgets.QMainWindow()
    ui = Ui_SongWindow()
    ui.setupUi(SongWindow)
    SongWindow.show()
    sys.exit(app.exec_())
